export { default as Footer } from './Footer/Footer'
export { default as Navbar } from './Navbar/Navbar'
export { default as Main } from './Main/Main'
export { default as About } from './About/About'
export { default as Resume } from './Resume/Resume'
export { default as Blog } from './Blog/Blog'
export { default as Contact } from './Contact/Contact'
export { default as Projects } from './Projects/Projects'